-- DropForeignKey
ALTER TABLE "RSVP" DROP CONSTRAINT "RSVP_sessionId_fkey";

-- AddForeignKey
ALTER TABLE "RSVP" ADD CONSTRAINT "RSVP_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session"("id") ON DELETE CASCADE ON UPDATE CASCADE;
